### ISSUE TITLE
Plans for Fully OpenSource/Free Tools

### ISSUE THREAD

**Issue by neeewwww** [pashpashpash/vault-ai#57]
Do you have any plans to use a fully free and opensource tools/api instead of OpenAI?
Also retrieve data from a private corpus, like Google Drive?

**Comment by pashpashpash** [comment]
@neeewwww I am working on publishing a [Vault Zapier app](https://vault.pash.city/business) so that you can hook up things like google drive and other things easily. WRT replacing openai, I haven't seen a better alternative to OpenAI that gives similar quality answers. But pinecone can be replaced with something like Weaviate quite easily.
